print("         \\|||||/        ")
print("         ( O O )         ")
print("|--ooO-----(_)----------|")
print("|                       |")
print("|      Hello World      |")
print("|                       |")
print("|------------------Ooo--|")
print("         |__||__|        ")
print("          ||  ||         ")
print("         ooO  Ooo        ")